#!/usr/bin/env bash
# bash script that tranfers file from client to server
if [ $# -le 0 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n"
else
	scp -i $4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $1 $3@$2:~/
fi
