#!/usr/bin/env bash
# script to install nginx and configure its landing page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
ufw allow ssh
ufw enable
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo service Nginx restart
