#!/usr/bin/env bash
# script to install nginx and configure its landing page

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^\tserver_name.*/a \\n\trewrite ^\/redirect_me/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
