#!/usr/bin/env bash
# Script for installing HAproxy in server and configure it

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install haproxy=2.0\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\t server 3944-web-01 34.75.232.87:80 check\n\tserver 3944-web-02 107.23.155.109:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
