#!/usr/bin/env bash
# printing best school 10 times and bestschool+hi in the 9th iteration
i=0
while [ $i -le 10 ]
do
	if [ "$i" == 9 ]
	then
		echo "Best School"
		echo "Hi"
		((i++))
	else
		echo "Best School"
		((i++))
	fi
done
